/* autogenerated by Processing revision 1293 on 2024-02-23 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class piano extends PApplet {


SinOsc sine;

float d;
float dd;
float re;
float rere;
float mi;
float fa;
float fafa;
float so;
float soso;
float ra = 440.0f;
float rara;
float si;
float r;

int octave;

public void setup(){
  /* size commented out by preprocessor */;
  sine = new SinOsc(this);
  // oto no onntei wo sakusei
  r = pow(2.0f,1.0f/12.0f);
  text(r,900,350);
  rara = ra*r;
  si = rara*r;
  soso = ra/r;
  so = soso/r;
  fafa = so/r;
  fa = fafa/r;
  mi = fa/r;
  rere = mi/r;
  re = rere/r;
  dd = re/r;
  d = dd/r;
  
  octave = 3;
}

public void octaveup(){
  if(octave<6){
  d = d*2.0f;
  dd = dd*2.0f;
  re = re*2.0f;
  rere = rere*2.0f;
  mi = mi*2.0f;
  fa = fa*2.0f;
  fafa = fafa*2.0f;
  so = so*2.0f;
  soso = soso*2.0f;
  ra = ra*2.0f;
  rara = rara*2.0f;
  si = si*2.0f;
  octave = octave+1;
}
}

public void octavedown(){
  if(octave>1){
  d = d/2.0f;
  dd = dd/2.0f;
  re = re/2.0f;
  rere = rere/2.0f;
  mi = mi/2.0f;
  fa = fa/2.0f;
  fafa = fafa/2.0f;
  so = so/2.0f;
  soso = soso/2.0f;
  ra = ra/2.0f;
  rara = rara/2.0f;
  si = si/2.0f;
  octave = octave-1;
}
}

public void draw(){
  background(0xFFA4E6F2);
  fill(255);
  rectMode(CENTER);
  rect(width/2,height/2,700,350);
  stroke(0);
  rect(width/2,height/2,700,350);
  // kokken ha y zahyo wo 75 ni kuttukeru
  fill(0);
  rectMode(CORNER);
  rect(225,75,50,200);
  rect(325,75,50,200);
  rect(525,75,50,200);
  rect(625,75,50,200);
  rect(725,75,50,200);
  stroke(0);
  rect(225,75,50,200);
  rect(325,75,50,200);
  rect(525,75,50,200);
  rect(625,75,50,200);
  rect(725,75,50,200);
  
  // mouse no iti ni oujite irowo kaeru 
  int X = mouseX;
  int Y = mouseY;
  noStroke();
  fill(100);
  rectMode(CORNER);
  if(((150<=X)&&(X<250)&&(275<=Y)&&(Y<=425))||((150<=X)&&(X<225)&&(75<=Y)&&(Y<275))){
    rect(150,75,75,350);
    rect(150,275,100,150);
  }
  // do#
  if((225<=X)&&(X<275)&&(75<=Y)&&(Y<275)){
    rect(225,75,50,200);
  }
  // re
  if(((250<=X)&&(X<350)&&(275<=Y)&&(Y<=425))||((275<=X)&&(X<325)&&(75<=Y)&&(Y<275))){
    rect(275,75,50,350);
    rect(250,275,100,150);
  }
  // re#
  if((325<=X)&&(X<375)&&(75<=Y)&&(Y<275)){
    rect(325,75,50,200);
  }
  // mi
  if(((350<=X)&&(X<450)&&(275<=Y)&&(Y<=425))||((375<=X)&&(X<450)&&(75<=Y)&&(Y<275))){
    rect(375,75,75,350);
    rect(350,275,100,150);
  }
  // fa
  if(((450<=X)&&(X<550)&&(275<=Y)&&(Y<=425))||((450<=X)&&(X<525)&&(75<=Y)&&(Y<275))){
    rect(450,75,75,350);
    rect(450,275,100,150);
  }
  // fa#
  if((525<=X)&&(X<575)&&(75<=Y)&&(Y<275)){
    rect(525,75,50,200);
  }
  // so
  if(((550<=X)&&(X<650)&&(275<=Y)&&(Y<=425))||((575<=X)&&(X<625)&&(75<=Y)&&(Y<275))){
    rect(575,75,50,350);
    rect(550,275,100,150);
  }
  // so#
  if((625<=X)&&(X<675)&&(75<=Y)&&(Y<275)){
    rect(625,75,50,200);
  }
  // ra
  if(((650<=X)&&(X<750)&&(275<=Y)&&(Y<=425))||((675<=X)&&(X<725)&&(75<=Y)&&(Y<275))){
    rect(675,75,50,350);
    rect(650,275,100,150);
  }
  // ra#
  if((725<=X)&&(X<775)&&(75<=Y)&&(Y<275)){
    rect(725,75,50,200);
  }
  // si
  if(((750<=X)&&(X<850)&&(275<=Y)&&(Y<=425))||((775<=X)&&(X<850)&&(75<=Y)&&(Y<275))){
    rect(775,75,75,350);
    rect(750,275,100,150);
  }
  
  // sen wo hiku
  stroke(0);
  line(250,275,250,425);
  line(350,275,350,425);
  line(450,75,450,425);
  line(550,275,550,425);
  line(650,275,650,425);
  line(750,275,750,425);
  // zukei owari
  fill(255,0,255);
  textSize(32);
  text("Pitch level = " +octave,380,50);
  textSize(24);
  text("UP Pitch: push A key",380,450);
  text("DOWN Pitch: push S key",365,475);
}

public void mousePressed(){
  float volume = 0.1f;
  float X = mouseX;
  float Y = mouseY;
  // do
  if(((150<=X)&&(X<250)&&(275<=Y)&&(Y<=425))||((150<=X)&&(X<225)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(d,volume);
    fill(100);
    rect(150,75,100,350);
  }
  // do#
  if((225<=X)&&(X<275)&&(75<=Y)&&(Y<275)){
    volume = 0.1f + (Y-75)/250;
    sine.play(dd,volume);
  }
  // re
  if(((250<=X)&&(X<350)&&(275<=Y)&&(Y<=425))||((275<=X)&&(X<325)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(re,volume);
  }
  // re#
  if((325<=X)&&(X<375)&&(75<=Y)&&(Y<275)){
    volume = 0.1f + (Y-75)/250;
    sine.play(rere,volume);
  }
  // mi
  if(((350<=X)&&(X<450)&&(275<=Y)&&(Y<=425))||((375<=X)&&(X<450)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(mi,volume);
  }
  // fa
  if(((450<=X)&&(X<550)&&(275<=Y)&&(Y<=425))||((450<=X)&&(X<525)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(fa,volume);
  }
  // fa#
  if((525<=X)&&(X<575)&&(75<=Y)&&(Y<275)){
    volume = 0.1f + (Y-75)/250;
    sine.play(fafa,volume);
  }
  // so
  if(((550<=X)&&(X<650)&&(275<=Y)&&(Y<=425))||((575<=X)&&(X<625)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(so,volume);
  }
  // so#
  if((625<=X)&&(X<675)&&(75<=Y)&&(Y<275)){
    volume = 0.1f + (Y-75)/250;
    sine.play(soso,volume);
  }
  // ra
  if(((650<=X)&&(X<750)&&(275<=Y)&&(Y<=425))||((675<=X)&&(X<725)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(ra,volume);
  }
  // ra#
  if((725<=X)&&(X<775)&&(75<=Y)&&(Y<275)){
    volume = 0.1f + (Y-75)/250;
    sine.play(rara,volume);
  }
  // si
  if(((750<=X)&&(X<850)&&(275<=Y)&&(Y<=425))||((775<=X)&&(X<850)&&(75<=Y)&&(Y<275))){
    volume = 0.1f + (Y-75)/500;
    sine.play(si,volume);
  }
}

public void mouseReleased() {
 sine.stop();
}

public void keyPressed(){
  if(key == 'a')octaveup();
  if(key == 's')octavedown();
}


  public void settings() { size(1000, 500); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "piano" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
